### ISSUE TITLE
Urdu Devanagari Open Bible Stories

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#112]
Urdu Devanagari Open Bible Stories

**Comment by JesniJ** [comment]
1.Some of the story headings ends with hyphen,  Story numbers are [ 2,6,24,25,32,44,48 ]
![image](https://user-images.githubusercontent.com/102143707/177101927-70ed1e67-ae8b-4c4a-89d2-f5a3c3f022b7.png)
![image](https://user-images.githubusercontent.com/102143707/177101994-db048ad2-2611-4af0-8209-5dbbd78f809b.png)




2.18th story heading has comma after the story number instead of dot.
![image](https://user-images.githubusercontent.com/102143707/177102045-7ee4170d-0023-467b-b848-8d6facfb0b43.png)

3. Some of the stories in many places comma,-,"  in the starting of the lines.
![image](https://user-images.githubusercontent.com/102143707/177102098-1ff1a9f8-d885-49ec-acbe-f0816e9f5672.png)
![image](https://user-images.githubusercontent.com/102143707/177102154-3b2eac5f-1b45-4ed6-90cc-d86290249b80.png)


 Story numbers are [ 28, 35. 40, 42,43, 45, ]
4. 38th story, in heading story number is missing.
![image](https://user-images.githubusercontent.com/102143707/177102201-c7ba6821-7a66-4f7d-9891-9fdb46882393.png)


5. 39th story "Yi" is there in the middle of the passage.

![image](https://user-images.githubusercontent.com/102143707/177102246-7c132c07-b952-4738-b224-96251d640438.png)

6. 45,46,48,50 stories in heading there is no dot after story number.
![image](https://user-images.githubusercontent.com/102143707/177102295-117a5df2-3be8-433c-b8b3-d2f2c64e67a1.png)

7. In all stories many sentences ends with hyphen.
8. Most of the stories in the references verses starts and ends with  hyphen.
![image](https://user-images.githubusercontent.com/102143707/177102354-d691e06d-0a07-47fb-96ad-0af831019fd7.png)
As discussed moving this issue back to in-progress.

**Comment by AnuMonachan** [comment]
Urdu Devanagari issue 3,7,8 are not fixed (they are using - in place of . or । (hindi full stop) in stories ) needs discussion with team how to proceed
Fixed all other issues

**Comment by JesniJ** [comment]
Testing completed and issues in Urdu Devanagari are fixed.
