### ISSUE TITLE
Kachhi OT Bible (4 Books)

### ISSUE THREAD

**Issue by AnuMonachan** [Bridgeconn/vachancontentrepository#128]
OT Books - Psa, Pro, Ecc & Sng

**Comment by AnnCherianA** [comment]
@selvabenz please test this issue and share your feedback

**Comment by AnnCherianA** [comment]
@selvabenz  thank you for testing the content.
Could you also check whether the UI features are working -highlights, bookmarks etc

**Comment by selvabenz** [comment]
Working as expected

**Comment by selvabenz** [comment]
- [ ] Video Bible can be shown some related gateway language like Gujarati
![Video bible can be shown some related gateway language like Gujarati](https://user-images.githubusercontent.com/121541505/224685663-82236688-6f00-43c3-9d73-d35018dd0aea.png)

- [ ] Assamese audio Bible is shown in Koli, Kachi language, instead can we keep some related gateway language like Gujarati
![Assamese audio bible is shown in Koli, Kachi language, instead can we keep some related gateway language like Gujarati](https://user-images.githubusercontent.com/121541505/224686055-134a3041-009a-4493-86e9-d5962aecc089.png)

- [ ] Instead of Bengali can we have related gateway language
![instead of Bengali can we have related gateway language ](https://user-images.githubusercontent.com/121541505/224686221-37791205-61c0-46d1-ac03-3af644c3a1a0.png)

- [ ] Is there any way to get back the deleted notes?
![is there any way to get the notes back which i have deleted?](https://user-images.githubusercontent.com/121541505/224686603-87b7cc09-cf2e-440f-b777-3ec262165108.png)

- [ ] Navigation pointing to a different book but not the immediate book - (Gal-Mar)
![Navigation Gal-Mar](https://user-images.githubusercontent.com/121541505/224687003-7b16be9a-bcec-45ed-9218-ebaa2a37c8cd.png)

- [ ] Can we keep the commentary as relevant as the language group?
![can we keep the commentary as relevant as the language group?](https://user-images.githubusercontent.com/121541505/224687813-b62c2f45-0d57-4483-b1f0-769992308edf.png)

- [ ] Can we keep the dictionary as relevant as the language group?
![can we keep the dictionary as relevant as the language group?](https://user-images.githubusercontent.com/121541505/224687909-39c7c1d8-2c04-4537-b9fb-b62a5e30807e.png)

- [ ] Bengali info-graphic page English text is shown
![Bengali info-graphic page English text is shown](https://user-images.githubusercontent.com/121541505/224688268-22bc2954-0ee9-457e-8eb5-18bc6cb8303b.png)

**Comment by selvabenz** [comment]
> @selvabenz Could you also check whether the UI features are working -highlights, bookmarks etc

Features mentioned above are working as expected

**Comment by AnnCherianA** [comment]
@selvabenz  please mention the names of the basic features that you tested

**Comment by AnnCherianA** [comment]
Moving back to QA for update

**Comment by selvabenz** [comment]
> @selvabenz please mention the names of the basic features that you tested

UI features - highlights, bookmarks, notes, dictionary, commentary, info-graphic, audio and video are tested and working expected.
